app/urls.py
__author__ = 'Tadej'
from . import views
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^login/',  views.login, name='login'),
    url(r'^login_action/',  views.login_action, name='login_action'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout_view/', views.logout_view, name='logout'),
    url(r'^import_data/', views.import_data, name='import_data'),
    url(r'^import_assignments_data/', views.import_assignments_data, name='import_assignments_data'),
    url(r'^settings/schedule/save_simple/', views.save_simple_schedule_settings, name='save_simple_schedule_settings'),
    url(r'^settings/schedule/add_slot/', views.schedule_add_slot, name='schedule_add_slot'),
    url(r'^settings/schedule/add_parallel_slots/', views.schedule_add_parallel_slots, name='schedule_add_parallel_slots'),
    url(r'^settings/schedule/change_slot_length/', views.schedule_change_slot_time, name='schedule_change_slot_length'),
    url(r'^settings/schedule/delete_slot/', views.delete_slot, name='schedule_delete_slot'),
    url(r'^settings/schedule/change_start_time', views.change_start_time, name='change_start_time'),
    url(r'^settings/schedule/rename_slot', views.rename_slot, name='rename_slot'),
    url(r'^settings/schedule/up/', views.move_slot_up, name='move_slot_up'),
    url(r'^settings/schedule/down/', views.move_slot_down, name='move_slot_down'),
    url(r'^settings/schedule/', views.schedule_settings, name='schedule_settings'),
    url(r'^papers/view/', views.view_paper, name='view_papers'),
    url(r'^papers/update/', views.update_paper, name='update_paper'),
    url(r'^papers/add_to_schedule/', views.add_paper_to_schedule, name='add_paper_to_schedule'),
    url(r'^papers/remove_from_schedule/', views.remove_paper_from_schedule, name='remove_paper_from_schedule'),
    url(r'^papers/change_lock/', views.lock_paper, name='lock_paper'),
    url(r'^clustering/basic/', views.basic_clustering, name='basic_clustering'),
    url(r'^clustering/settings/', views.clustering_settings, name='clustering_settings'),
    url(r'^clustering/results/all', views.clustering_results, name='clustering_results_all'),
    url(r'^clustering/results/assigned', views.clustering_results_assigned, name='clustering_results_assigned'),
    url(r'^conference/list/', views.conference_list, name='conference_list'),
    url(r'^conference/create/', views.create_conference, name='create_conference'),
    url(r'^conference/delete/', views.delete_conference, name='delete_conference'),
    url(r'^conference/copy/', views.copy_conference, name='copy_conference'),
    url(r'^conference/rename/action', views.rename_conference_action, name='rename_conference_action'),
    url(r'^conference/rename/', views.rename_conference, name='rename_conference'),
    url(r'^conference/export/', views.export_schedule, name='export_schedule'),

]

diploma/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls', namespace='app'))
]

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<script src="{% static "app/bootstrap/js/jQuery.js" %}"></script>
<link rel="stylesheet" type="text/css" href="{% static "app/bootstrap/css/bootstrap.min.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "app/bootstrap/css/style.css"%}"/>
<link rel="stylesheet" type="text/css" href="{% static "app/nvd3/nv.d3.css" %}"/>
<script type="text/javascript" src="{% static "app/bootstrap/js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "app/d3/d3.min.js" %}"></script>
<script type="text/javascript" src="{% static "app/nvd3/nv.d3.min.js" %}"></script>
<head>
    <meta charset="UTF-8">
    <title>Diploma</title>
</head>
<body>
<div class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <div class="navbar-brand">
                <a href = "/app/index/">
                    Manual program
                </a>
            </div>
            <div class="navbar-brand">
                <a href="/app/settings/schedule" >
                    Schedule
                </a>
            </div>
            <div class="navbar-brand">
                <a href="{% url 'app:clustering_settings' %}" >
                    Automatic scheduling
                </a>
            </div>
            <div class="navbar-brand">
                <a href="{% url 'app:clustering_results_all' %}" >
                    Clustering results
                </a>
            </div>
            <div class="navbar-brand">
                <a href="{% url 'app:export_schedule' %}" >
                    Export schedule
                </a>
            </div>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a class="navbar-brand" href="/app/conference/list" >
                    Change conference
                </a>
            </li>
            <li>
                <a class="navbar-brand" href="/app/logout_view">
                    Logout
                </a>
            </li>
        </ul>
    </div>
</div>
{% block content %}

{% endblock content %}
</body>
</html>

templates/app/clustering_results.html
{% extends "app/base.html" %}
{% block content %}
    {% load filters %}
    {% load staticfiles %}
    {% load tags %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="{% static "app/js/cluserting_results.js" %}"></script>
    <div class="hidden" id="coordsx">
        {% for i in num_papers|custom_range %}
            <input type="hidden", id="x{{ paper_ids|get_element_at:i }}", value="{{ paper_coords_x|get_element_at:i }}"/>
        {% endfor %}
    </div>
    <div class="hidden" id="coordsy">
        {% for i in num_papers|custom_range %}
            <input type="hidden", id="y{{ paper_ids|get_element_at:i }}", value="{{ paper_coords_y|get_element_at:i }}"/>
        {% endfor %}
    </div>
    <div class="hidden" id="clusters">
        {% for i in num_papers|custom_range %}
            <input type="hidden", id="c{{ paper_ids|get_element_at:i }}", value="{{ paper_clusters|get_element_at:i }}"/>
        {% endfor %}
    </div>
    <div class="hidden" id="titles">
        {% for i in num_papers|custom_range %}
            <input type="hidden", id="x{{ paper_ids|get_element_at:i }}", value="{{ paper_titles|get_element_at:i }}"/>
        {% endfor %}
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-2">
                <div class="panel panel-default fixed-side-panel" id="paper-panel">
                    <div class="panel-heading">Papers</div>
                    <div class="panel-body scrollable">
                        <ul class="list-group">
                            {% for i in num_papers|custom_range %}
                                <a href="/app/papers/view/?id={{ paper_ids|get_element_at:i }}" name="paper">
                                    <li class="list-group-item cluster{{ paper_clusters|get_element_at:i }}">
                                        {{ paper_titles|get_element_at:i }}
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <div class="panel panel-default" id="maindiv">
                    <div class="panel-heading">
                        Clustering results (
                        {%  if all == True %}
                        <a href="{% url 'app:clustering_results_assigned' %}">
                            Show only papers that were newly assigned to the schedule
                        </a>
                        {% else %}
                        <a href="{% url 'app:clustering_results_all' %}">
                            Show all papers
                        </a>
                        {% endif %}
                    )
                    </div>
                    <div class="panel-body" id="schedule_div">
                        {% if num_papers == 0 %}
                            <p>There are currently no clustering results.</p>
                            <p>Clustering results will be displayed after running automatic scheduling</p>
                        {% else %}
                            <svg style='height:595px'/>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/app/clustering_settings.html
{% extends "app/base.html" %}
{% load filters %}
{% block content %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static "app/js/clustering_settings.js" %}"></script>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Automatic scheduling settings
                    </div>
                    <form method="post" action="{% url 'app:basic_clustering' %}">
                        {% csrf_token %}
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-9">
                                    <label for="method">Clustering function</label>
                                    <select id="method" name="method" class="form-control"
                                           placeholder="">
                                        <option value="aff">Affinity propagation</option>
                                        {# <option value="dbs">DBSCAN</option>  #}
                                        <option value="hie">Hierarchical clustering</option>
                                        <option value="kme">K-Means</option>
                                        <option value="msh">Mean-shift</option>
                                        <option value="kmm">Mini batch K-Means</option>
                                    </select>
                                </div>
                            </div>
                            <br/>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Function parameters
                                </div>
                                <div class="panel-body">
                                    <div id="aff" name="params" class="row">
                                        <!--
                                        <div class="col-xs-3">
                                            <label for="num_clusters">Maximum number of iterations</label>
                                            <input type="text" id="num_clusters" name="num_clusters" class="form-control"
                                                   placeholder="Number of clusters" />
                                        </div>
                                        -->
                                    </div>
                                    <div id="ncl" name="params" class="row">
                                        <div class="col-xs-3">
                                            <label for="num_clusters">Number of clusters</label>
                                            <input type="text" id="num_clusters" name="num_clusters" class="form-control"
                                                   placeholder="Number of clusters" />
                                        </div>
                                    </div>
                                    <div id="msh" name="params" class="row">
                                        <div class="col-xs-3">
                                            <label for="num_clusters">Cluster sizes (1 to 100)</label>
                                            <input type="text" id="band" name="band" class="form-control"
                                                   placeholder="25" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br/>
                            <div class="panel panel-default">
                                <div class="panel-heading">Select which data should be used for clustering</div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="input-group">
                                                <input value="1" id="usetitles" name="usetitles" type="checkbox" class="form-inline"/>
                                                <label for="usetitles"> Use Titles</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="input-group">
                                                <input id="useabstracts" name="useabstracts" type="checkbox" class="form-inline"/>
                                                <label for="useabstracts"> Use Abstracts</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="input-group">
                                                <input id="assign" name="assign" type="checkbox" class="form-inline"
                                                        {% if has_assignment_data == False %}
                                                            disabled
                                                        {% endif %}
                                                />
                                                <label for="assign"> Use Assignment data</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br/>
                            <div class="row">
                                <div class="col-xs-12">
                                    <label for="keywords">Use only the following words for computing clusters</label>
                                    <input type="text" id="keywords" name="keywords" class="form-control"
                                           placeholder="word1 word2 word3" />
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary">Start automatic scheduling</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/app/conference_list.html
{% extends "app/base.html" %}
{% load filters %}
{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Conferences
                    </div>
                    <div class="panel-body">
                    {% if num_conferences == 0 %}
                        You currently have no saved conferences. Use the button below to create one
                    {% else %}
                        {%  for title, id in form_data %}
                            <div class="list-group-item">
                                <div class="row">
                                    <div class="col-xs-6">
                                        <form class="form-inline" action="{% url 'app:index' %}" method="post">
                                            {% csrf_token %}
                                            <input class="hidden" id="conference" name="conference" value="{{id}}"/>
                                            <button type="submit" class="btn btn-link">{{ title }}</button>
                                        </form>
                                    </div>
                                    <div class="col-xs-2">
                                        <form class="form-inline" action="{% url 'app:rename_conference' %}" method="post">
                                            {% csrf_token %}
                                            <input class="hidden" id="conference" name="conference" value="{{id}}"/>
                                            <button type="submit" class="btn btn-default">Rename conference</button>
                                        </form>
                                    </div>
                                    <div class="col-xs-2">
                                        <form class="form-inline" action="{% url 'app:copy_conference' %}" method="post">
                                            {% csrf_token %}
                                            <input class="hidden" id="conference" name="conference" value="{{id}}"/>
                                            <button type="submit" class="btn btn-success">Copy conference structure</button>
                                        </form>
                                    </div>
                                    <div class="col-xs-2">
                                        <form class="form-inline" action="{% url 'app:delete_conference' %}" method="post">
                                            {% csrf_token %}
                                            <input class="hidden" id="conference" name="conference" value="{{id}}"/>
                                            <button type="submit" class="btn btn-danger">Delete conference</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    </div>
                    <div class="panel-footer">
                        <div class="panel-body">
                            <div class="row-fluid">
                                <form action="{% url 'app:create_conference' %}" method="post"
                                    class="form-inline">
                                    {% csrf_token %}
                                    <div class="input-group">
                                        <input type="text" id="title" name="title" class="form-control"
                                               placeholder="Conference title">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Create conference</button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/app/conference_rename.html
{% extends "app/base.html" %}
{% load filters %}
{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Rename conference
                    </div>
                    <form method="post" action="{% url 'app:rename_conference_action' %} ">
                        {% csrf_token %}
                        <div class="panel-body">
                            <input hidden value="{{ id }}" id="conference" name="conference"/>
                            <label for="oldname">Old name</label>
                            <input disabled class="form-control" id="oldname", name="oldname" value="{{ old_name }}">

                            <label for="newname">New name</label>
                            <input class="form-control" id="newname", name="newname">
                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary">Rename conference</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/app/index.html
{% extends "app/base.html" %}
{% block content %}
    {% load filters %}
    {% load staticfiles %}
    {% load tags %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="{% static "app/js/index.js" %}"></script>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-2">
                <div class="panel panel-default fixed-side-panel" id="paper-panel">
                    <div class="panel-heading">Papers</div>
                    <div class="panel-body scrollable">
                        Imported papers: {{ num_papers }}
                        Imported authors: {{ num_authors }}
                        <ul class="list-group">
                            {% for i in num_papers|custom_range %}
                                <li class="list-group-item cluster{{ paper_clusters|get_element_at:i }}">
                                    <a href="/app/papers/view/?id={{ paper_ids|get_element_at:i }}" name="paper">
                                        {{ paper_titles|get_element_at:i }}
                                        ({{ paper_lengths|get_element_at:i }}min)
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                        <a href="/app/papers/view/" class="btn btn-primary">Add paper</a>
                        <br/><br/>
                        <form method="post" action="{% url 'app:import_data' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form papers_form %}
                            {% buttons %}
                                <button type="submit" class="btn btn-primary">
                                   Import papers
                                </button>
                            {% endbuttons %}
                        </form>
                        <br/>
                        <form method="post" action="{% url 'app:import_assignments_data' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form assignments_form %}
                            {% buttons %}
                                <button type="submit" class="btn btn-primary">
                                   Import assigments
                                </button>
                            {% endbuttons %}
                        </form>
                        <br/><br/>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <div class="panel panel-default" id="maindiv">
                    <div class="panel-heading">
                        Schedule (
                        {% for i in num_days|custom_range %}
                            {% if  i != day %}
                                <a href="/app/index/?day={{ i }}">Day {{ i|add:1 }}</a>
                            {% else %}
                                Day {{ i|add:1 }}
                            {% endif %}
                            {% if i|add:1 < num_days %}
                                |
                            {% endif %}
                        {% endfor %}
                        )
                    </div>
                    <div class="panel-body" id="schedule_div">
                        <div class="table">
                            {% for row in settings_list %}
                                <div class="panel panel-default">
                                    {% for col in row %}
                                        {% if forloop.counter0|mod:3 == 0%}
                                            <div class="row">
                                        {% endif %}
                                        <div class="col-md-{{ row|allign_schedule }}">
                                            <div class="well" name="slot">
                                                <div class="row">
                                                    <div class="col-xs-5">
                                                        Slot {{ forloop.parentloop.counter }}<br/>
                                                        Length: {{ col }}min <br/>
                                                        Free time: {{ col }}min <br/>
                                                    </div>
                                                    <div class="col-xs-2">
                                                        <form class="form-inline" method="post" action="{% url 'app:move_slot_up' %}">
                                                            {% csrf_token %}
                                                            <input hidden id="slot" name="slot" value="{{ forloop.parentloop.counter }}">
                                                            <input hidden id="day" name="day" value="{{ day }}">
                                                            <button class="btn btn-default">Move slot up</button>
                                                        </form>
                                                        <form class="form-inline" method="post" action="{% url 'app:move_slot_down' %}">
                                                            {% csrf_token %}
                                                            <input hidden id="slot" name="slot" value="{{ forloop.parentloop.counter }}">
                                                            <input hidden id="day" name="day" value="{{ day }}">
                                                            <button class="btn btn-default">Move slot down</button>
                                                        </form>
                                                    </div>
                                                </div>
                                                <br/>
                                                <!-- Display all the papers in the slot -->
                                                {% get_paper schedule day forloop.parentloop.counter0 forloop.counter0 as papers %}
                                                {% for paper in papers %}
                                                    <div class="well">
                                                        <div class="row">
                                                            <a href="/app/papers/view/?id={{ paper }}" name="paper">
                                                            <div class="col-xs-8">
                                                                {{ paper_dict|get_element_at:paper }}
                                                            </div>
                                                                </a>
                                                            <div class="col-xs-4">
                                                                {% if paper_locked|get_element_at:paper %}
                                                                    <p class="text-right">
                                                                        <input type="submit" class="btn btn-sm btn-danger"
                                                                               value="Unlock paper" name="lock-button"
                                                                                id="{{ paper }}"/>
                                                                    </p>

                                                                {% else %}
                                                                    <p class="text-right">
                                                                        <input type="submit" class="btn btn-sm btn-primary"
                                                                               value="Lock paper" name="lock-button"
                                                                                id="{{ paper }}"/>
                                                                    </p>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                                <input class="hidden" , value="{{ forloop.counter0 }}" id="col" ,
                                                       name="col"/>
                                                <input class="hidden" , value="{{ forloop.parentloop.counter0 }}"
                                                       id="row" , name="row"/>
                                                {% with num_lines=col|div:50 %}
                                                    {% for b in num_lines|custom_range %}
                                                        <br/>
                                                    {% endfor %}
                                                {% endwith %}
                                            </div>
                                        </div>
                                        {% if forloop.counter0|mod:3 == 2%}
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                    {# </div> #}
                                </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock content %}

templates/app/view_paper.html
{% extends "app/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Edit paper
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'app:update_paper' %}">
                        {% csrf_token %}
                        {% bootstrap_formset formset %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">
                               Save
                            </button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
        </div>

{% endblock %}