app/urls.py
__author__ = 'Tadej'
from . import views
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^login/',  views.login, name='login'),
    url(r'^login_action/',  views.login_action, name='login_action'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout_view/', views.logout_view, name='logout'),
    url(r'^import_data/', views.import_data, name='import_data'),
    url(r'^import_assignments_data/', views.import_assignments_data, name='import_assignments_data'),
    url(r'^settings/schedule/save_simple/', views.save_simple_schedule_settings, name='save_simple_schedule_settings'),
    url(r'^settings/schedule/add_slot/', views.schedule_add_slot, name='schedule_add_slot'),
    url(r'^settings/schedule/add_parallel_slots/', views.schedule_add_parallel_slots, name='schedule_add_parallel_slots'),
    url(r'^settings/schedule/change_slot_length/', views.schedule_change_slot_time, name='schedule_change_slot_length'),
    url(r'^settings/schedule/delete_slot/', views.delete_slot, name='schedule_delete_slot'),
    url(r'^settings/schedule/change_start_time', views.change_start_time, name='change_start_time'),
    url(r'^settings/schedule/rename_slot', views.rename_slot, name='rename_slot'),
    url(r'^settings/schedule/up/', views.move_slot_up, name='move_slot_up'),
    url(r'^settings/schedule/down/', views.move_slot_down, name='move_slot_down'),
    url(r'^settings/schedule/', views.schedule_settings, name='schedule_settings'),
    url(r'^papers/view/', views.view_paper, name='view_papers'),
    url(r'^papers/update/', views.update_paper, name='update_paper'),
    url(r'^papers/add_to_schedule/', views.add_paper_to_schedule, name='add_paper_to_schedule'),
    url(r'^papers/remove_from_schedule/', views.remove_paper_from_schedule, name='remove_paper_from_schedule'),
    url(r'^papers/change_lock/', views.lock_paper, name='lock_paper'),
    url(r'^clustering/basic/', views.basic_clustering, name='basic_clustering'),
    url(r'^clustering/settings/', views.clustering_settings, name='clustering_settings'),
    url(r'^clustering/results/all', views.clustering_results, name='clustering_results_all'),
    url(r'^clustering/results/assigned', views.clustering_results_assigned, name='clustering_results_assigned'),
    url(r'^conference/list/', views.conference_list, name='conference_list'),
    url(r'^conference/create/', views.create_conference, name='create_conference'),
    url(r'^conference/delete/', views.delete_conference, name='delete_conference'),
    url(r'^conference/copy/', views.copy_conference, name='copy_conference'),
    url(r'^conference/rename/action', views.rename_conference_action, name='rename_conference_action'),
    url(r'^conference/rename/', views.rename_conference, name='rename_conference'),
    url(r'^conference/export/', views.export_schedule, name='export_schedule'),

]

diploma/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls', namespace='app'))
]

templates/app/settings/schedule.html
{% extends "app/base.html" %}
{% load filters %}
{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Settings</div>
                    <div class="panel-body">
                        <form action="{% url 'app:save_simple_schedule_settings' %}" method="post" class="form-inline">
                            {% csrf_token %}
                            <div class="input-group col-md-3">
                                <div class="input-group-addon">Number of days</div>
                                <input type="text" class="form-control" name="num_days" id="num_days"
                                       value={{ num_days }}
                                               placeholder="1"/>
                            </div>
                            <div class="input-group col-md-3">
                                <div class="input-group-addon">Minutes per slot</div>
                                <input type="text" class="form-control" name="base_time" id="base_time"
                                       value={{ base_time }}
                                               placeholder="60"/>
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Schedule (
                        {% for i in num_days|custom_range %}
                            {% if  i != day %}
                                <a href="/app/settings/schedule/?day={{ i }}">Day {{ i|add:1 }}</a>
                            {% else %}
                                Day {{ i|add:1 }}
                            {% endif %}
                            {% if i|add:1 < num_days %}
                                |
                            {% endif %}
                        {% endfor %}
                        )
                    </div>
                    <div class="panel-body">
                        <form action="{% url 'app:change_start_time' %}" method="post">
                            {% csrf_token %}
                            <input class="hidden" , value={{ day }} id="day", name="day"/>
                            <div class="input-group">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">Change starting time</button>
                            </span>
                            <input type="text" id="time" name="time" class="form-control"
                                   placeholder="{{ start_time }}">
                            </div>

                            <label class="">{{ time_error }}</label>
                        </form>
                        <table class="table">
                            {% for row in settings_list %}
                                <div class="row">
                                    {% for col in row|wrap_int_in_list %}
                                        <div class="col-md-{{ row|allign_schedule }}">
                                            <div class="well">
                                                <div class="row">
                                                    <div class="col-xs-3">
                                                        Slot {{ forloop.parentloop.counter }}<br/>
                                                    </div>
                                                    <div class="col-xs-9">
                                                        <p class="text-right">
                                                            {# Form for deleting a slot #}
                                                            <form class="form-inline"
                                                                  action="{% url 'app:schedule_delete_slot' %}" method="post">
                                                                {% csrf_token %}
                                                                <input class="hidden" , id="row" , name="row" ,
                                                                       value="{{ forloop.parentloop.counter0 }}"/>
                                                                <input class="hidden" , id="col" , name="col" ,
                                                                       value="{{ forloop.counter0 }}"/>
                                                                <input class="hidden" , value="{{ day }}" id="day",
                                                                       name="day"/>
                                                                <button type="submit" class="btn btn-xs btn-danger">
                                                                    Delete
                                                                </button>
                                                            </form>
                                                        </p>
                                                    </div>
                                                </div>
                                                <br/>
                                                <form class="form-inline"
                                                      action="{% url 'app:schedule_change_slot_length' %}"
                                                      method="post">
                                                    {% csrf_token %}
                                                    <input class="hidden" , id="row" , name="row" ,
                                                           value="{{ forloop.parentloop.counter0 }}"/>
                                                    <input class="hidden" , id="col" , name="col" ,
                                                           value="{{ forloop.counter0 }}"/>
                                                    <input class="hidden" , value={{ day }} id="day", name="day"/>

                                                    <div><label for="len">Length:</label></div>
                                                    <div class="input-group input-group-sm">
                                                        <input type="text" id="len" name="len" class="form-control"
                                                               placeholder="" value="{{ col }}">
                                                        <span class="input-group-btn">
                                                            <button type="submit" class="btn btn-primary">Change</button>
                                                        </span>
                                                    </div>
                                                </form>
                                                {# Form for renaming a slot #}
                                                <form class="form-inline"
                                                      action="{% url 'app:rename_slot' %}" method="post">
                                                    {% csrf_token %}
                                                    <input class="hidden" , id="row" , name="row" ,
                                                           value="{{ forloop.parentloop.counter0 }}"/>
                                                    <input class="hidden" , id="col" , name="col" ,
                                                           value="{{ forloop.counter0 }}"/>
                                                    <input class="hidden" , value="{{ day }}" id="day",
                                                           name="day"/>
                                                    <div><label for="len">Name:</label></div>
                                                    <div class="input-group input-group-sm">
                                                        <input type="text" id="name" name="name" class="form-control"
                                                               placeholder="" value="{{ names|get_element_at:day|get_element_at:forloop.parentloop.counter0|get_element_at:forloop.counter0 }}">
                                                        <span class="input-group-btn">
                                                            <button type="submit" class="btn btn-success">Rename</button>
                                                        </span>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="panel-footer">
                        <div class="panel-body">
                            <div class="row-fluid">
                                <div class="col-md-1">
                                    <form action="{% url 'app:schedule_add_slot' %}" method="post" class="form-inline">
                                        {% csrf_token %}
                                        <input class="hidden" , value={{ day }} id="day", name="day"/>
                                        <button type="submit" class="btn btn-primary">Add slot</button>
                                    </form>
                                </div>
                                <div class="col-md-4">
                                    <form action="{% url 'app:schedule_add_parallel_slots' %}" method="post"
                                          class="form-inline">
                                        {% csrf_token %}
                                        <input class="hidden" , value={{ day }} id="day", name="day"/>

                                        <div class="input-group">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Add parallel slots</button>
                                        </span>
                                        <input type="text" id="num_slots" name="num_slots" class="form-control"
                                               placeholder="Number of slots">
                                        </div>
                                        <label class="">{{ error }}</label>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}